language: php
php:
  - 5.6
  - 7.0

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require "fxp/composer-asset-plugin:*"
  - composer update

script:
  - vendor/bin/codecept build
  - vendor/bin/codecept run

notifications:
  email: false
